// Stonetop gear catalogue — transcribed from Book I: the Inventory insert (p.142),
// Common items (p.95) and Special items (pp.96–97). Loaded before the inline script.
//   load: 0 = small item (no load; counts toward the 4+Prosperity small-item marks),
//         1 = ◆, 2 = ◆◆, 'other' = not carried on your person (animals, immobile kit).
//   pips: a finite track printed on the item (hours of oil, uses of whisky).
//   ammo: the item's ammo states, first = full.  value: Trade & Barter Value 0–4.
window.GEAR = {
  common: [
    // weapons
    {id:'g_bow',       cat:'Weapons', name:'Bow & iron arrows',   load:1, tags:'near, x piercing', ammo:['plenty','low ammo','all out'], value:0},
    {id:'g_arrows',    cat:'Weapons', name:'Extra arrows',        load:1, tags:'x piercing', ammo:['plenty left','low ammo','all out'], value:0},
    {id:'g_hatchet',   cat:'Weapons', name:'Hatchet, iron',       load:1, tags:'hand, thrown, x piercing', value:0},
    {id:'g_javelins',  cat:'Weapons', name:'Javelins, a few, iron', load:1, tags:'thrown, x piercing, +1 damage', ammo:['have some','all out'], value:0},
    {id:'g_knife',     cat:'Weapons', name:'Knife or dagger, iron', load:0, tags:'hand', value:0},
    {id:'g_longspear', cat:'Weapons', name:'Long spear, iron',    load:2, tags:'reach, x piercing', value:0},
    {id:'g_mallet',    cat:'Weapons', name:'Mallet, iron or wood', load:1, tags:'hand', value:0},
    {id:'g_mattock',   cat:'Weapons', name:'Mattock, iron',       load:1, tags:'close, messy, x piercing, awkward', value:0},
    {id:'g_maul',      cat:'Weapons', name:'Maul, iron',          load:2, tags:'close, forceful, awkward', value:0},
    {id:'g_sling',     cat:'Weapons', name:'Sling',               load:0, tags:'near, reload, awkward', ammo:['plenty','low ammo','all out'], value:0},
    {id:'g_spear',     cat:'Weapons', name:'Spear, iron',         load:1, tags:'close, thrown, x piercing', value:0},
    {id:'g_staff',     cat:'Weapons', name:'Staff',               load:1, tags:'close', value:0},
    // armor
    {id:'g_shield',    cat:'Armor', name:'Shield',      load:2, tags:'+1 armor, +1 Readiness on a 7+ to Defend', value:0},
    {id:'g_hides',     cat:'Armor', name:'Thick hides', load:2, tags:'1 armor, warm', value:0},
    // clothing
    {id:'g_clothes',   cat:'Clothing', name:'Change of clothes', load:1, tags:'', value:0},
    {id:'g_cloak',     cat:'Clothing', name:'Cloak',             load:1, tags:'warm', value:0},
    {id:'g_socks',     cat:'Clothing', name:'Extra socks',       load:0, tags:'', value:0},
    {id:'g_gloves',    cat:'Clothing', name:'Gloves',            load:0, tags:'', value:0},
    {id:'g_needle',    cat:'Clothing', name:'Needle & thread',   load:0, tags:'', value:0},
    // fire & light
    {id:'g_oil',       cat:'Fire & light', name:'Extra oil',  load:1, tags:'for lamp/lantern; useless as a weapon', pips:{kind:'hours',max:5}, value:0},
    {id:'g_firewood',  cat:'Fire & light', name:'Firewood',   load:2, tags:'enough to last 1 full night; reach, area', value:0},
    {id:'g_lamp',      cat:'Fire & light', name:'Oil lamp',   load:1, tags:'close, area, crude', pips:{kind:'hours',max:3}, value:0},
    {id:'g_rushlight', cat:'Fire & light', name:'Rushlight',  load:0, tags:'lasts ~15–30 minutes; close, crude', value:0},
    {id:'g_tinderbox', cat:'Fire & light', name:'Tinderbox',  load:0, tags:'slow', value:0},
    {id:'g_torch',     cat:'Fire & light', name:'Torch',      load:1, tags:'lasts ~1 hour; reach, area, dangerous', value:0},
    // travel gear
    {id:'g_bedroll',   cat:'Travel gear', name:'Bedroll',       load:1, tags:'recover 1d6 extra HP when you Make Camp', value:0},
    {id:'g_blanket',   cat:'Travel gear', name:'Blanket',       load:1, tags:'warm', value:0},
    {id:'g_bowstring', cat:'Travel gear', name:'Bowstring, spare', load:0, tags:'', value:0},
    {id:'g_coppers',   cat:'Travel gear', name:'Handful of coppers', load:0, tags:'', value:0},
    {id:'g_messkit',   cat:'Travel gear', name:'Mess kit',      load:1, tags:'requires fire & water; 1 use of supplies feeds up to 4', value:0},
    {id:'g_rope',      cat:'Travel gear', name:'Rope, ~25 ft',  load:1, tags:'', value:0},
    {id:'g_sack',      cat:'Travel gear', name:'Sack (empty)',  load:0, tags:'', value:0},
    {id:'g_sledge',    cat:'Travel gear', name:'Sledge / litter / travois', load:2, tags:'roll-out', value:0},
    {id:'g_snowshoes', cat:'Travel gear', name:'Snow-shoes',    load:1, tags:'', value:0},
    {id:'g_waterskin', cat:'Travel gear', name:'Waterskin',     load:0, tags:'', value:0},
    {id:'g_whetstone', cat:'Travel gear', name:'Whetstone',     load:0, tags:'', value:0},
    {id:'g_whisky',    cat:'Travel gear', name:'Whisky, skin',  load:0, tags:'', pips:{kind:'uses',max:2}, value:0},
    {id:'g_whistle',   cat:'Travel gear', name:'Whistle',       load:0, tags:'', value:0},
    // household goods
    {id:'g_awl',       cat:'Household', name:'Awl',        load:0, tags:'', value:0},
    {id:'g_chalk',     cat:'Household', name:'Chalk',      load:0, tags:'', value:0},
    {id:'g_charcoal',  cat:'Household', name:'Charcoal',   load:0, tags:'', value:0},
    {id:'g_clayjar',   cat:'Household', name:'Clay jar',   load:0, tags:'', value:0},
    {id:'g_cloth',     cat:'Household', name:'Cloth / rag', load:0, tags:'', value:0},
    {id:'g_comb',      cat:'Household', name:'Comb',       load:0, tags:'', value:0},
    {id:'g_cup',       cat:'Household', name:'Cup',        load:0, tags:'', value:0},
    {id:'g_littlebox', cat:'Household', name:'Little box', load:0, tags:'', value:0},
    {id:'g_sawdust',   cat:'Household', name:'Sawdust',    load:0, tags:'', value:0},
    {id:'g_shovel',    cat:'Household', name:'Shovel',     load:1, tags:'', value:0},
    {id:'g_tallow',    cat:'Household', name:'Tallow',     load:0, tags:'', value:0},
    {id:'g_twine',     cat:'Household', name:'Twine / cord', load:0, tags:'', value:0}
  ],
  // Special items: you must Trade & Barter for these (p.96). * = Value 2 to get 1 (maybe 2) piercing.
  special: [
    {id:'s_mace',      cat:'Weapons of war', name:'Mace or flail, iron',  load:1, tags:'close, forceful', value:1},
    {id:'s_battleaxe', cat:'Weapons of war', name:'Battleaxe, iron',      load:1, tags:'close, messy', value:1, note:'Value 2 to get 1 (maybe 2) piercing'},
    {id:'s_shortsword',cat:'Weapons of war', name:'Short sword, iron',    load:1, tags:'hand, close', value:1, note:'Value 2 to get 1 (maybe 2) piercing'},
    {id:'s_sword',     cat:'Weapons of war', name:'Sword, iron',          load:1, tags:'close, +1 damage', value:1, note:'Value 2 to get 1 (maybe 2) piercing'},
    {id:'s_warhammer', cat:'Weapons of war', name:'Warhammer, iron',      load:1, tags:'close, 2 piercing', value:1},
    {id:'s_crossbow',  cat:'Weapons of war', name:'Crossbow',             load:1, tags:'far, +1 damage, x piercing, reload', ammo:['plenty','low ammo','all out'], value:1},
    {id:'s_compbow',   cat:'Weapons of war', name:'Composite bow',        load:1, tags:'far, +1 damage, x piercing', ammo:['plenty','low ammo','all out'], value:1, note:'Value 2 to get 1 (maybe 2) piercing'},
    {id:'s_cuirass',   cat:'Armor', name:'Cuirass, boiled leather',      load:1, tags:'1 armor', value:1},
    {id:'s_hauberk',   cat:'Armor', name:'Hauberk / cuirass / scale, iron or bronze', load:2, tags:'2 armor, warm, cumbersome', value:2},
    {id:'s_vest',      cat:'Armor', name:'Vest, brigandine, fancy',      load:1, tags:'2 armor, warm', value:3},
    {id:'s_candle',    cat:'Light sources', name:'Candle',            load:0, tags:'lasts ~1 hour; close, area', value:0},
    {id:'s_lantern',   cat:'Light sources', name:'Lantern',           load:1, tags:'close, area', pips:{kind:'hours',max:5}, value:0},
    {id:'s_bullseye',  cat:'Light sources', name:'Bullseye lantern',  load:1, tags:'near', pips:{kind:'hours',max:5}, value:1},
    {id:'s_smalltool', cat:'Tools & trades', name:'Small metal tool (chisel, file, shears…)', load:0, tags:'', value:0},
    {id:'s_vial',      cat:'Tools & trades', name:'Glass vial',        load:0, tags:'fragile', value:0},
    {id:'s_tackle',    cat:'Tools & trades', name:'Block & tackle',    load:1, tags:'', value:0},
    {id:'s_instrument',cat:'Tools & trades', name:'Instrument (harp, lute, fiddle…)', load:1, tags:'', value:1},
    {id:'s_metaltools',cat:'Tools & trades', name:'Metal tools (drill, prybar, saw…)', load:1, tags:'', value:0},
    {id:'s_mirror',    cat:'Tools & trades', name:'Mirror, hand-held, polished bronze', load:1, tags:'', value:1},
    {id:'s_tradecommon',cat:'Tools & trades', name:'Common trade tools (pottery, weaving, distilling…)', load:'other', tags:'immobile', value:1},
    {id:'s_tradeuncommon',cat:'Tools & trades', name:'Uncommon trade tools (carpentry, chandlery, beekeeping…)', load:'other', tags:'immobile', value:2},
    {id:'s_tradespecial',cat:'Tools & trades', name:'Specialized trade tools (smithing, glassblowing, scribing…)', load:'other', tags:'immobile', value:3},
    {id:'s_slate',     cat:'Writing', name:'Slate and chalk',          load:1, tags:'', value:0},
    {id:'s_wax',       cat:'Writing', name:'Wax tablet and stylus',    load:1, tags:'', value:0},
    {id:'s_parchment', cat:'Writing', name:'Parchment, a few sheets',  load:0, tags:'fragile', value:1},
    {id:'s_vellum',    cat:'Writing', name:'Fine vellum, a few sheets', load:0, tags:'fragile', value:2},
    {id:'s_ink',       cat:'Writing', name:'Ink, vial and quills',     load:0, tags:'', value:1},
    {id:'s_bookp',     cat:'Writing', name:'Empty book, parchment',    load:1, tags:'fragile', value:1},
    {id:'s_bookv',     cat:'Writing', name:'Empty book, fine vellum',  load:1, tags:'fragile', value:2},
    {id:'s_wheelbarrow',cat:'Transport', name:'Wheelbarrow',           load:'other', tags:'', value:1},
    {id:'s_cart',      cat:'Transport', name:'Cart or sleigh',         load:'other', tags:'requires donkey/mule/horse', value:2},
    {id:'s_wagon',     cat:'Transport', name:'Wagon',                  load:'other', tags:'requires mule/horse', value:3},
    {id:'s_spareparts',cat:'Transport', name:'Spare parts for wagon/cart/sleigh', load:'other', tags:'immobile', pips:{kind:'uses',max:3}, value:2},
    {id:'s_bendis',    cat:'Exotic', name:'Bendis root',   load:0, tags:'fumes repel perversions of nature; lasts ~1 hour; reach, area', value:1},
    {id:'s_bezoar',    cat:'Exotic', name:'Bezoar',        load:0, tags:'swallow to cure any poison', value:1},
    {id:'s_naphtha',   cat:'Exotic', name:'Naphtha',       load:1, tags:'burns hot & sticky; damage d8; thrown, area, dangerous, ignores armor', pips:{kind:'uses',max:3}, value:1},
    {id:'s_silverdagger',cat:'Exotic', name:'Silver-alloy dagger', load:1, tags:'hand', value:2},
    {id:'s_salt',      cat:'Trade goods', name:'Salt (a little box)',     load:0, tags:'', value:0},
    {id:'s_finewhisky',cat:'Trade goods', name:'Skin of whisky, fine',    load:0, tags:'share a use with someone to get advantage on Persuade', pips:{kind:'uses',max:2}, value:0},
    {id:'s_pursecopper',cat:'Trade goods', name:'Purse of coppers',       load:1, tags:'~10 handfuls', value:0},
    {id:'s_firkin',    cat:'Trade goods', name:'Firkin of whisky, fine',  load:2, tags:'', value:1},
    {id:'s_silvers',   cat:'Trade goods', name:'Handful of silvers',      load:0, tags:'', value:1},
    {id:'s_barrelcommon',cat:'Trade goods', name:'Barrel of whisky, common', load:'other', tags:'immobile', value:1},
    {id:'s_barrelfine',cat:'Trade goods', name:'Barrel of whisky, fine',  load:'other', tags:'immobile', value:2},
    {id:'s_pursesilver',cat:'Trade goods', name:'Purse of silvers',       load:1, tags:'~10 handfuls', value:2},
    {id:'s_surplus',   cat:'Trade goods', name:'1 Surplus of various trade goods', load:'other', tags:'immobile', value:2},
    {id:'s_dog',       cat:'Livestock & beasts', name:'Dog, follower',  load:'other', tags:'keen-nosed, pick 2 more; HP 6; damage d6 (hand, grabby); instinct to get distracted; cost: training', value:1},
    {id:'s_goat',      cat:'Livestock & beasts', name:'Goat',           load:'other', tags:'sure-footed, curious, hungry; HP 3; damage d4 (hand); instinct to explore; butcher for 4 provisions (6 uses)', value:1},
    {id:'s_sheep',     cat:'Livestock & beasts', name:'Sheep',          load:'other', tags:'timid, hardy, wooly; HP 3; damage d4 (hand); instinct to follow the herd; butcher for 4 provisions (6 uses)', value:1},
    {id:'s_pig',       cat:'Livestock & beasts', name:'Pig',            load:'other', tags:'keen-nosed, stubborn, gluttonous, clever; HP 6; damage d4 (hand); instinct to eat anything; butcher for provisions (d6+10 uses)', value:1},
    {id:'s_donkey',    cat:'Livestock & beasts', name:'Donkey',         load:'other', tags:'hardy, sure-footed, cautious, slow; HP 10; damage d4+2 (hand, forceful); instinct to be stubborn', value:2},
    {id:'s_mule',      cat:'Livestock & beasts', name:'Mule, follower?', load:'other', tags:'large, hardy, sure-footed, cautious, keen-nosed, sterile; HP 14; damage d6+1 (hand, close); instinct to avoid danger; cost: care & grooming', value:3},
    {id:'s_horse',     cat:'Livestock & beasts', name:'Horse, follower?', load:'other', tags:'large, powerful, keen-nosed, swift or hardy; HP 10; damage d6+3 (hand, close, forceful); instinct to panic; cost: care & grooming', value:3}
  ]
};
