// GM-side reference data, hand-summarised from Book I: threat types with their GM moves
// (pp.284–287), the basic GM moves (p.178) and principles (p.192). Loaded after moves.js.
window.THREAT_TYPES = [
  {key:'affliction', name:'Affliction', page:284, gist:'Behaviours, circumstances, or conditions that make people suffer, bring them into conflict, or make them fret — a pox, a feud, a drought, a prejudice.',
   moves:['Worsen or quicken','Spread to others / suck others in','Mutate, take on a new form or aspect','Eat away at something or someone','Strip someone of honor or dignity','Drive someone to desperation','Justify selfishness, neglect','Drive a wedge between people','Cause delusion, stubbornness, foolishness','Sow panic or despair','Trigger shortages, hoarding','Prompt violence, hatred, blame'],
   examples:['The black pox (to infect and spread)','Braith\'s feud with Thecla (to make people pick sides)','The drought (to deplete resources)','Resentment toward the Hillfolk (to prevent cooperation)']},
  {key:'beast', name:'Beast', page:284, gist:'Monsters, animals, or NPCs driven by basic need and instinct — a creature, a pack, or a whole species.',
   moves:['Show up where it\'s not wanted','Stalk or pursue prey','Protect its home or family','Make a show of strength, aggression','Build or expand a nest, den, lair','Modify its environment','Flee or panic or rage','Consume something (or someone)','Grow or diminish, in size or numbers'],
   examples:['The cave bears (to fill their bellies, protect their young)','The nailadd swarm (to breed and spread out)','Orub the Hagr (to compulsively shape his environment)']},
  {key:'institution', name:'Institution', page:285, gist:'People, groups, or positions with power in a community — a cult, a council, a priesthood. It acts through individuals invested in its influence.',
   moves:['Sway public opinion','Put someone in their place','Change a rule, law, or custom','Acquire leverage, resources, influence','Denounce something or someone','Support a course of action','Recruit new members or minions','Squabble amongst themselves','Change leadership','Negotiate a deal or treaty','Send someone else to do their dirty work'],
   examples:['Aratis\'s priesthood (to preserve civilization, at all costs)','Marshedge Town Council (to maintain the status quo)','The nascent town council (to keep the PCs in check)']},
  {key:'macguffin', name:'MacGuffin', page:285, gist:'A thing — object, place, or secret — that stirs up conflict. Its instinct is about how it causes trouble, not what it does.',
   moves:['Reveal a secret','Draw attention to itself','Point to something else','Generate envy, fear, discord','Weigh heavily, become a burden','Be the target of theft','Go missing','Perform its function, heedlessly','Fail at the worst possible moment','Leave its mark on someone or something','Become something greater, or lesser'],
   examples:['The Chronicle\'s vault of artifacts (to harbor badness)','The Blood-quenched Sword (to encourage violence)','The aetherium weather vane (to inspire jealousy)']},
  {key:'rabble', name:'Rabble', page:286, gist:'A group united by emotion, blood, or circumstance rather than purpose. Its instinct is how the group behaves; individuals may not share it.',
   moves:['Grow or gather in numbers','Claim territory or resources','Fall under a (new) leader\'s sway','Undergo internal turmoil','Make a show of strength or numbers','Declare an enemy or an alliance','Turn on one of their own','Overwhelm a position or a weaker group','Despoil, loot, pillage, burn','Refuse to be controlled or contained','Disperse, scatter, flee'],
   examples:['Hillfolk refugees (to not fit in)','Daedre the Red\'s bandits (to do whatever the hell they want)','Heledd\'s family (to close ranks and protect their own)']},
  {key:'magical', name:'Magical entity', page:286, gist:'Spirits, Fae, the Things Below, gods and their agents — beings of magic and power, bound by strange laws, often acting subtly or through intermediaries.',
   moves:['Spy on someone, unseen or from afar','Sense powerful longings or emotions','Appear in glimpses, dreams, visions','Offer service, secrets, power','Demand an oath or sacrifice','Lay a curse','Twist a bargain to its favor','Send forth minions to do its bidding','Shape its environs, per its nature','Pursue alien goals','Foster rivalries with similar powers','Grow or diminish in strength'],
   examples:['Hec\'tumel, Slithering One (to smother life, hope, and light)','Mother-of-Spiders (to see her many children spread)','Blush-of-Dawn the Fae (to be adored)']},
  {key:'villain', name:'Villain', page:287, gist:'An individual with the ruthlessness, drive, and power to make life awful for many. Acts through minions, from strength, with a backup plan.',
   moves:['Grasp power, recklessly','Gain followers or allies','Find someone\'s weakness','Make an offer, with strings attached','Demand concessions, obedience, or respect','Make threats, veiled or not','Outmaneuver their enemies','Attack cautiously, holding reserves','Attack ruthlessly, with little warning','Reveal preparations made in advance','Sacrifice another to advance a goal','Betray an ally or a trust','Take a prisoner','Do the unthinkable'],
   examples:['Brennan (to maintain or increase his power)','Marc, Hillfolk slaver (to glorify himself and his clan)','The Eyeless Crinwin (to set free the Living Darkness)']},
  {key:'wildcard', name:'Wildcard', page:287, gist:'An individual who causes trouble because they are a mystery, or because the PCs care about them but can\'t trust them. Make triangles between wildcards and PCs.',
   moves:['Aggressively pursue their instinct','Show their worth, or lack thereof','Display the contents of their heart','Provide advice or aid, wanted or not','Reveal a secret, or keep one closely','Draw attention to themselves or others','Appear unannounced','Act strangely (for them)','Bear witness','Tell stories (true or not)','Make, keep, break, or demand a promise','Force an issue or a confrontation','Stand resolute and refuse to budge'],
   examples:['Esylt, the town busybody (to cling to how things "should" be)','Afon, Fae-touched Initiate of Danu (to act impulsively)','Muirdoc, the pretty boy (to toy with hearts)']}
];
window.GM_MOVES = ['Announce trouble (future or offscreen)','Reveal an unwelcome truth','Ask a provocative question','Put someone in a spot','Use up their resources','Turn their move back on them','Demonstrate a downside','Hurt someone','Separate them','Capture someone','Offer an opportunity (with or without a cost)','Tell them the consequences or requirements, then ask','Advance towards impending doom'];
window.GM_PRINCIPLES = ['Follow the rules','Begin and end with the fiction','Address the characters, not the players','Ask questions and build on the answers','Be a fan of the player characters','Embrace the fantastic and the mundane','Exploit the setting guide','Respect your prep','Give your characters life','Think offscreen, too','Bring it home','Let things breathe','Let things burn'];
window.RULES = (window.RULES || []).concat([
  {id:'gm-moves', cat:'GM', title:'GM moves', page:178, text:'When everyone looks to the GM to see what happens, on a 6−, or when the PCs ignore trouble, the GM makes a move: '+window.GM_MOVES.join('; ')+'. Make soft moves that set up trouble, and hard moves when the players hand you a golden opportunity.'},
  {id:'gm-principles', cat:'GM', title:'GM principles', page:192, text:window.GM_PRINCIPLES.join(' · ')+'.'},
  {id:'threat-write-up', cat:'GM', title:'Writing up a threat', page:282, text:'Name it and pick a type (Affliction, Beast, Institution, MacGuffin, Rabble, Magical entity, Villain, Wildcard). Put it on the Homefront, Nearby, or Distant tracker. Give it an instinct ("to …"). Describe it: where it came from, who is involved, how it ties to other threats. Optionally give it an impending doom (an irreversible bad end) with 2–4 grim portents — concrete, observable steps toward it that never dictate the PCs\' failure — plus stakes questions about the future, 2–4 custom GM moves, and player-facing custom moves. Between sessions: cross off resolved threats, tick portents, revise instincts, and move threats between trackers (p.298).'}
]);
